import { beforeEach, describe, expect, it } from 'vitest'
import request from 'supertest'
import { DateTime } from 'luxon'
import { STUDIO_TZ, dateKeyOf, studioInstant } from '@mizuki/shared'
import { createApp } from '../../app.js'
import { signAdminToken, COOKIE_NAMES } from '../../auth/tokens.js'
import {
  AdminUserModel,
  AuditLogModel,
  BookingModel,
  ScheduleRuleModel,
  SessionModel,
} from '../../models/index.js'
import { createBooking } from '../../services/bookingService.js'
import { materializeSessions } from '../../services/scheduleService.js'
import { makeCourseType, makeSession, makeStudent } from '../../test/factories.js'

/**
 * Deleting a class.
 *
 * The behaviour that matters is not the row going away. It is that a class generated by the
 * weekly timetable stays gone — the generator decides what to create by looking for slots with
 * no session row, so without an exception on the rule the class returns on the next tick, five
 * minutes later, with nothing on screen to explain it.
 */

const app = createApp()
let cookie: string

beforeEach(async () => {
  const admin = await AdminUserModel.create({
    name: 'Studio',
    email: 'studio@mizuki.com.sg',
    passwordHash: 'not-used-here',
    role: 'owner',
    active: true,
  })
  cookie = `${COOKIE_NAMES.admin}=${signAdminToken({
    sub: String(admin._id),
    email: admin.email,
    role: 'owner',
    v: admin.tokenVersion,
  })}`
})

/** A date far enough ahead to be future whenever this runs, and one safely behind. */
const future = () => DateTime.now().setZone(STUDIO_TZ).plus({ days: 30 })
const past = () => DateTime.now().setZone(STUDIO_TZ).minus({ days: 30 })

/**
 * A booking on a class that has already been taught.
 *
 * Written straight to the collection, because `createBooking` refuses a class that has started —
 * correctly, since nobody should be able to book their way into last month.
 */
async function pastBooking(sessionId: unknown, studentId: unknown, status = 'attended') {
  await SessionModel.updateOne({ _id: sessionId }, { $inc: { seatsTaken: 1 } })
  return BookingModel.create({ sessionId, studentId, status, source: 'admin_manual' })
}

describe('deleting a class', () => {
  it('removes one nobody is booked into', async () => {
    const course = await makeCourseType()
    const session = await makeSession({ courseTypeId: course._id, date: future().toFormat('yyyy-MM-dd') })

    await request(app).delete(`/api/admin/sessions/${session._id}`).set('Cookie', cookie).expect(200)

    expect(await SessionModel.countDocuments({ _id: session._id })).toBe(0)
  })

  it('refuses a future class students are still booked into, and says what to do', async () => {
    const course = await makeCourseType()
    const session = await makeSession({ courseTypeId: course._id, date: future().toFormat('yyyy-MM-dd') })
    const student = await makeStudent()
    await createBooking({ sessionId: session._id, studentId: student._id, source: 'admin_manual', notify: false })

    const res = await request(app)
      .delete(`/api/admin/sessions/${session._id}`)
      .set('Cookie', cookie)
      .expect(409)

    expect(res.body.error.message).toContain('Cancel it first')
    expect(await SessionModel.countDocuments({ _id: session._id })).toBe(1)
  })

  it('deletes it once it has been cancelled — the refusal is never a dead end', async () => {
    const course = await makeCourseType()
    const session = await makeSession({ courseTypeId: course._id, date: future().toFormat('yyyy-MM-dd') })
    const student = await makeStudent()
    await createBooking({ sessionId: session._id, studentId: student._id, source: 'admin_manual', notify: false })

    await request(app)
      .post(`/api/admin/sessions/${session._id}/cancel`)
      .set('Cookie', cookie)
      .send({ reason: 'Studio closed', notifyStudents: false })
      .expect(200)

    await request(app).delete(`/api/admin/sessions/${session._id}`).set('Cookie', cookie).expect(200)
    expect(await SessionModel.countDocuments({ _id: session._id })).toBe(0)
  })

  it('deletes a class that has already been taught, register and all', async () => {
    const course = await makeCourseType()
    const session = await makeSession({ courseTypeId: course._id, date: past().toFormat('yyyy-MM-dd') })
    const student = await makeStudent()
    await pastBooking(session._id, student._id)

    const res = await request(app)
      .delete(`/api/admin/sessions/${session._id}`)
      .set('Cookie', cookie)
      .expect(200)

    expect(res.body.bookingsRemoved).toBe(1)
    expect(await SessionModel.countDocuments({ _id: session._id })).toBe(0)
  })

  it('leaves no booking pointing at a class that no longer exists', async () => {
    const course = await makeCourseType()
    const session = await makeSession({ courseTypeId: course._id, date: past().toFormat('yyyy-MM-dd') })
    const student = await makeStudent()
    await pastBooking(session._id, student._id, 'confirmed')

    await request(app).delete(`/api/admin/sessions/${session._id}`).set('Cookie', cookie).expect(200)

    expect(await BookingModel.countDocuments({ sessionId: session._id })).toBe(0)
  })

  it('records what went, with enough detail to answer for it afterwards', async () => {
    const course = await makeCourseType()
    const session = await makeSession({
      courseTypeId: course._id,
      date: past().toFormat('yyyy-MM-dd'),
      title: 'Ikebana Workshop — Morning',
    })

    await request(app).delete(`/api/admin/sessions/${session._id}`).set('Cookie', cookie).expect(200)

    const entry = await AuditLogModel.findOne({ action: 'session.delete' }).lean()
    expect(entry!.reason).toContain('Ikebana Workshop — Morning')
    expect(entry!.actor).toContain('studio@mizuki.com.sg')
  })
})

describe('a class that came from the weekly timetable', () => {
  /** One weekly rule, materialised into real classes, exactly as the studio's timetable works. */
  async function weeklyRule() {
    const course = await makeCourseType()
    const from = DateTime.now().setZone(STUDIO_TZ).startOf('day')

    const rule = await ScheduleRuleModel.create({
      courseTypeId: course._id,
      title: 'IFDA Morning',
      recurrence: { freq: 'WEEKLY', byWeekday: [1, 2, 3, 4, 5, 6, 7], interval: 1 },
      startTime: '10:00',
      durationMins: 180,
      capacity: 8,
      effectiveFrom: from.toFormat('yyyy-MM-dd'),
      active: true,
    })

    await materializeSessions()
    return rule
  }

  it('stays deleted — the generator does not put it back on the next tick', async () => {
    const rule = await weeklyRule()
    const session = await SessionModel.findOne({ scheduleRuleId: rule._id }).sort({ startAt: 1 })
    const startAt = session!.startAt

    await request(app).delete(`/api/admin/sessions/${session!._id}`).set('Cookie', cookie).expect(200)

    // What the scheduled tick does every five minutes.
    await materializeSessions()

    expect(await SessionModel.countDocuments({ scheduleRuleId: rule._id, startAt })).toBe(0)
  })

  it('keeps generating every other date of that rule', async () => {
    const rule = await weeklyRule()
    const before = await SessionModel.countDocuments({ scheduleRuleId: rule._id })
    const session = await SessionModel.findOne({ scheduleRuleId: rule._id }).sort({ startAt: 1 })

    await request(app).delete(`/api/admin/sessions/${session!._id}`).set('Cookie', cookie).expect(200)
    await materializeSessions()

    expect(await SessionModel.countDocuments({ scheduleRuleId: rule._id })).toBe(before - 1)
  })

  it('records the date on the rule itself, so the reason is visible', async () => {
    const rule = await weeklyRule()
    const session = await SessionModel.findOne({ scheduleRuleId: rule._id }).sort({ startAt: 1 })

    await request(app).delete(`/api/admin/sessions/${session!._id}`).set('Cookie', cookie).expect(200)

    const after = await ScheduleRuleModel.findById(rule._id).lean()
    expect(after!.exceptions.map((d) => new Date(d as unknown as string).getTime())).toContain(
      session!.startAt.getTime(),
    )
  })
})

describe('the preview', () => {
  it('says what would go before anything goes', async () => {
    const course = await makeCourseType()
    const session = await makeSession({
      courseTypeId: course._id,
      date: past().toFormat('yyyy-MM-dd'),
      title: 'Bouquet Day',
    })
    const student = await makeStudent({ name: 'Aiko Tan' })
    await pastBooking(session._id, student._id)

    const res = await request(app)
      .get(`/api/admin/sessions/${session._id}/deletion`)
      .set('Cookie', cookie)
      .expect(200)

    expect(res.body.title).toBe('Bouquet Day')
    expect(res.body.isPast).toBe(true)
    expect(res.body.totalBookings).toBe(1)
    expect(res.body.attended).toBe(1)
    expect(res.body.studentNames).toEqual(['Aiko Tan'])
    expect(res.body.blockedReason).toBeNull()

    // A preview must not have changed anything.
    expect(await SessionModel.countDocuments({ _id: session._id })).toBe(1)
  })

  it('explains the one case it will not do', async () => {
    const course = await makeCourseType()
    const session = await makeSession({ courseTypeId: course._id, date: future().toFormat('yyyy-MM-dd') })
    const student = await makeStudent()
    await createBooking({ sessionId: session._id, studentId: student._id, source: 'admin_manual', notify: false })

    const res = await request(app)
      .get(`/api/admin/sessions/${session._id}/deletion`)
      .set('Cookie', cookie)
      .expect(200)

    expect(res.body.blockedReason).toContain('Cancel it first')
    expect(res.body.liveBookings).toBe(1)
  })

  it('says when a class comes from the weekly timetable', async () => {
    const course = await makeCourseType()
    const byHand = await makeSession({ courseTypeId: course._id, date: future().toFormat('yyyy-MM-dd') })

    const res = await request(app)
      .get(`/api/admin/sessions/${byHand._id}/deletion`)
      .set('Cookie', cookie)
      .expect(200)
    expect(res.body.fromWeeklyRule).toBe(false)
  })
})

/** Kept so an unused-import lint never quietly removes what the factories rely on. */
export const _unused = { dateKeyOf, studioInstant }
