import type { Types } from 'mongoose'
import { ACTIVE_BOOKING_STATUSES, ROSTER_STATUSES } from '@mizuki/shared'
import { BookingModel, ScheduleRuleModel, SessionModel, StudentModel } from '../models/index.js'
import { recordAudit } from './auditService.js'
import { AppError, NotFoundError } from '../errors.js'
import { logger } from '../logger.js'

/**
 * Removing a class from the calendar for good.
 *
 * Cancelling is the right answer for a class that was going to run and now is not: it tells
 * everyone booked, hands their course sessions back, and leaves the class on the calendar with a
 * reason. This is the other case — a class typed in twice, a wrong time, or a cancelled one the
 * studio no longer wants to look at — where the row itself is the problem.
 *
 * Two things make it more than a `deleteOne`. A class generated by a weekly rule comes straight
 * back on the next tick unless the rule is told to skip that date. And bookings outlive the
 * class they point at, so they go with it — otherwise a student's history shows a booking for a
 * class that cannot be loaded.
 */

export interface SessionDeletionPreview {
  id: string
  title: string
  startAt: Date
  /** Already taught, so there is history here rather than plans. */
  isPast: boolean
  cancelled: boolean
  /** Students still holding a place. Non-zero on a future class is what blocks deletion. */
  liveBookings: number
  /** Everyone who was ever on the register, including those who attended. */
  totalBookings: number
  attended: number
  studentNames: string[]
  /** Set when this class came from the weekly timetable rather than being added by hand. */
  fromWeeklyRule: boolean
  /** Why this cannot be deleted yet, in the studio's words, or null if it can. */
  blockedReason: string | null
}

export async function previewSessionDeletion(
  sessionId: Types.ObjectId | string,
  now: Date = new Date(),
): Promise<SessionDeletionPreview> {
  const session = await SessionModel.findById(sessionId).lean()
  if (!session) throw new NotFoundError('Class')

  const bookings = await BookingModel.find({ sessionId: session._id }).lean()
  const live = bookings.filter((b) => (ACTIVE_BOOKING_STATUSES as readonly string[]).includes(b.status))
  const onRegister = bookings.filter((b) => (ROSTER_STATUSES as readonly string[]).includes(b.status))

  const students = await StudentModel.find({ _id: { $in: onRegister.map((b) => b.studentId) } })
    .select('name')
    .lean()

  const isPast = session.startAt.getTime() < now.getTime()

  return {
    id: String(session._id),
    title: session.title,
    startAt: session.startAt,
    isPast,
    cancelled: session.status === 'cancelled',
    liveBookings: live.length,
    totalBookings: bookings.length,
    attended: bookings.filter((b) => b.status === 'attended').length,
    studentNames: students.map((s) => s.name),
    fromWeeklyRule: Boolean(session.scheduleRuleId),
    blockedReason: blockedReason(isPast, live.length),
  }
}

/**
 * Why not, or null.
 *
 * The one refusal worth making is a class that has not happened yet with students holding
 * places: deleting it would take their place away with no email and no course session returned,
 * and the first they would know of it is turning up to a locked door. Cancelling does all of
 * that properly, and leaves the class deletable straight afterwards — so the refusal costs one
 * extra click and is never a dead end.
 *
 * A class already taught is not refused. Its bookings are history, and history the studio wants
 * rid of is theirs to remove.
 */
function blockedReason(isPast: boolean, liveBookings: number): string | null {
  if (isPast || liveBookings === 0) return null

  return (
    `${liveBookings} student${liveBookings === 1 ? ' is' : 's are'} still booked into this class. ` +
    'Cancel it first — that tells them and gives back their course session — then you can delete it.'
  )
}

export interface SessionDeletionResult {
  title: string
  bookingsRemoved: number
  /** True when the weekly rule was told to skip this date so it is not generated again. */
  ruleExceptionAdded: boolean
}

export async function deleteSession(
  sessionId: Types.ObjectId | string,
  actor: string,
  now: Date = new Date(),
): Promise<SessionDeletionResult> {
  const session = await SessionModel.findById(sessionId)
  if (!session) throw new NotFoundError('Class')

  const live = await BookingModel.countDocuments({
    sessionId: session._id,
    status: { $in: ACTIVE_BOOKING_STATUSES },
  })

  const blocked = blockedReason(session.startAt.getTime() < now.getTime(), live)
  if (blocked) throw new AppError(409, 'has_bookings', blocked)

  /*
   * Told to skip this date before the class goes, not after.
   *
   * If the write below fails the class is still there, which is a no-op the studio can retry.
   * The other order risks a deleted class with the rule still generating it — the exact failure
   * this exists to prevent, arriving five minutes later with nothing on screen to explain it.
   */
  let ruleExceptionAdded = false
  if (session.scheduleRuleId) {
    const updated = await ScheduleRuleModel.updateOne(
      { _id: session.scheduleRuleId },
      { $addToSet: { exceptions: session.startAt } },
    )
    ruleExceptionAdded = updated.modifiedCount > 0
  }

  // Bookings outlive the class they point at, so they go with it.
  const removed = await BookingModel.deleteMany({ sessionId: session._id })

  await recordAudit({
    actor,
    action: 'session.delete',
    entity: 'Session',
    entityId: session._id,
    before: {
      title: session.title,
      dateKey: session.dateKey,
      startAt: session.startAt,
      status: session.status,
    },
    reason:
      `Deleted ${session.title} on ${session.dateKey}` +
      (removed.deletedCount ? `, along with ${removed.deletedCount} booking(s)` : '') +
      (ruleExceptionAdded ? '. The weekly timetable will not generate it again.' : ''),
  })

  await session.deleteOne()

  logger.info(
    { session: String(session._id), bookings: removed.deletedCount, ruleExceptionAdded },
    'Class deleted',
  )

  return {
    title: session.title,
    bookingsRemoved: removed.deletedCount ?? 0,
    ruleExceptionAdded,
  }
}
